# Generated by Django 3.2.8 on 2021-10-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_build_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="json_value",
            field=models.JSONField(
                blank=True, default=dict, help_text="A json value", null=True
            ),
        ),
    ]
