# docker-compose up -d
version: "2"

services:
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
     - POSTGRES_HOST_AUTH_METHOD=trust

  uwsgi:
    restart: always
    container_name: uwsgi
    build: .

    # Add your GitHub key and secret here
    environment:
      - SOCIAL_AUTH_GITHUB_KEY=
      - SOCIAL_AUTH_GITHUB_SECRET=
    volumes:
      - .:/code
      - ./spackmon/static:/var/www/static
      - ./spackmon/images:/var/www/images
    links:
      - db

  nginx:
    restart: always
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /etc/ssl/private:/etc/ssl/private:ro
    volumes_from:
      - uwsgi
    links:
      - uwsgi
