name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches_ignore: []

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup black environment
        run: conda create --quiet --name black pyflakes

      - name: Check formatting with black
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate black
          pip install black
          black --check spackmon


  testing:
    needs: formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup testing environment
        run: conda create --quiet --name testing pytest

      - name: Test spackmon
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate testing
          pip install -r requirements.txt
          python runtests.py
